# Site settings
title: Aditya Mehta
email: aditya.mhta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Data Scientist
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://adityamehta.co" # the base hostname & protocol for your site
twitter_username: 
github_username:  
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
